[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Optimizations
optimizer = true
optimizer_runs = 200

# Testing
verbosity = 3
gas_reports = ["*"]

# Coverage
fuzz_runs = 256

[rpc_endpoints]
anvil = "http://localhost:8545"
